# Generated by Django 4.2.7 on 2025-02-01 13:18

from django.db import migrations, models

try:
    from progressbar import progressbar
except:
    def progressbar(range):
        return range

def compute_submission_status(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Submission = apps.get_model('dtf', 'Submission')

    status_order = {
        "skip": 0,
        "successful": 1,
        "unknown": 2,
        "unstable": 3,
        "failed": 4,
        "broken": 5
    }

    for submission in progressbar(Submission.objects.using(db_alias).all().iterator()):
        status = None
        for test in submission.tests.all():
            test_status = test.status
            if status is None or status_order[test_status] > status_order[status]:
                status = test_status
        if status is None:
            submission.status = "unknown"
        else:
            submission.status = status

        submission.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0023_fix_json_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('skip', 'skip'), ('successful', 'successful'), ('unstable', 'unstable'), ('unknown', 'unknown'), ('failed', 'failed'), ('broken', 'broken')], default='unknown', max_length=20),
        ),
        migrations.RunPython(compute_submission_status, migrations.RunPython.noop),
    ]
