# Generated by Django 4.2.7 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0024_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('skip', 'skip'), ('successful', 'successful'), ('unstable', 'unstable'), ('unknown', 'unknown'), ('failed', 'failed'), ('broken', 'broken')], default='skip', max_length=20),
        ),
    ]
