
name: "Build Documentation"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@8.1.3
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
