name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.11, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-devel.txt
    - name: Run Tests
      run: |
        coverage run --source='dtf' --omit='*tests*,*migrations*,*wsgi*,*asgi*' manage.py test -v2
    - name: Publish coverage report to coveralls
      uses: AndreMiras/coveralls-python-action@v20201129
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: python-${{ matrix.python-version }}
